### ISSUE TITLE
Symbol keys

### ISSUE THREAD

**Issue by Daniel-ltw** [Ishotihadus/usamin#3]
Is there a section in the c native extension that does symbol keys? 

If there is, could we actually have that feature implemented as an option? 

I could write a recursive method in ruby to do the conversion, but that will not be efficient.

**Comment by Ishotihadus** [comment]
No. Usamin.parse, Usamin::Value#eval, and Usamin::Value#eval_r don't have an option which is equivalent to :symbolize_names option of JSON.parse.

However, Usamin::Hash objects can be accessed by symbolized index.

```rb
data = Usamin.load('{"a": 5}')
#=> {"a"=>5}
data['a']
#=> 5
data[:a]
#=> 5

data = Usamin.parse('{"a": 5}')
#=> {"a"=>5}
[6] pry(main)> data['a']
#=> 5
[7] pry(main)> data[:a]
#=> nil
```

**Comment by Daniel-ltw** [comment]
Does this work for nested hash?

**Comment by Ishotihadus** [comment]
Support :symbolize_names option in usamin [v7.7.10](https://github.com/Ishotihadus/usamin/releases/tag/v7.7.10).
